function GUI_Aspirantes
    % GUI para capturar número de aspirantes y ejecutar informeCompleto.m

    % Crear ventana
    f = figure('Name','Captura de Aspirantes', ...
               'NumberTitle','off', ...
               'Position',[500 300 500 250], ...
               'Color','white', ...
               'MenuBar','none', ...
               'Resize','off');

    % === Panel izquierda: Número de aspirantes ===
    uicontrol('Parent',f, 'Style','text', ...
              'Position',[30 180 180 30], ...
              'String','Número de Aspirantes:', ...
              'FontSize',12, ...
              'HorizontalAlignment','left', ...
              'BackgroundColor','white');

    hEdit = uicontrol('Parent',f, 'Style','edit', ...
                      'Position',[220 185 80 30], ...
                      'FontSize',12, ...
                      'BackgroundColor','white', ...
                      'String','5'); % Valor por defecto

    % === Panel derecha: Porcentajes de participación esperados ===
    uicontrol('Parent',f, 'Style','text', ...
              'Position',[310 180 180 20], ...
              'String','Porcentajes de participación esperados', ...
              'FontWeight','bold', ...
              'FontSize',10, ...
              'HorizontalAlignment','left', ...
              'BackgroundColor','white');

    % Alumnos
    uicontrol('Parent',f, 'Style','text', ...
              'Position',[310 150 80 20], ...
              'String','Alumnos (%):', ...
              'BackgroundColor','white', ...
              'HorizontalAlignment','left');
    hEditAlumnos = uicontrol('Parent',f, 'Style','edit', ...
              'Position',[400 150 60 25], ...
              'String','60', ...
              'BackgroundColor','white');

    % Profesores
    uicontrol('Parent',f, 'Style','text', ...
              'Position',[310 115 80 20], ...
              'String','Profesores (%):', ...
              'BackgroundColor','white', ...
              'HorizontalAlignment','left');
    hEditProfesores = uicontrol('Parent',f, 'Style','edit', ...
              'Position',[400 115 60 25], ...
              'String','60', ...
              'BackgroundColor','white');

    % Administrativos
    uicontrol('Parent',f, 'Style','text', ...
              'Position',[310 80 90 20], ...
              'String','Administrativos (%):', ...
              'BackgroundColor','white', ...
              'HorizontalAlignment','left');
    hEditAdministrativos = uicontrol('Parent',f, 'Style','edit', ...
              'Position',[400 80 60 25], ...
              'String','60', ...
              'BackgroundColor','white');

    % Botón Aceptar
    uicontrol('Parent',f, 'Style','pushbutton', ...
              'String','Aceptar', ...
              'FontSize',12, ...
              'Position',[170 20 160 40], ...
              'BackgroundColor',[0.4 0.4 0.4], ...
              'ForegroundColor','white', ...
              'Callback',@(src,event) aceptarValor());

    %% Función del botón
    function aceptarValor()
        valor = str2double(get(hEdit, 'String'));
        alumnos = str2double(get(hEditAlumnos, 'String')) / 100;
        profesores = str2double(get(hEditProfesores, 'String')) / 100;
        administrativos = str2double(get(hEditAdministrativos, 'String')) / 100;

        if isnan(valor) || valor < 1 || mod(valor,1) ~= 0
            errordlg('Ingrese un número entero válido de aspirantes','Error');
            return;
        end
        if any(isnan([alumnos, profesores, administrativos])) || any([alumnos, profesores, administrativos] < 0) || any([alumnos, profesores, administrativos] > 1)
            errordlg('Los porcentajes deben estar entre 0 y 100','Error');
            return;
        end

        % Enviar al workspace
        assignin('base','Aspirantes',valor);
        assignin('base','media_participacion_alumnos',alumnos);
        assignin('base','media_participacion_profesores',profesores);
        assignin('base','media_participacion_administrativos',administrativos);

        try
            run('VotoPorBloque.m');
        catch ME
            errordlg(['Error en el script: ' ME.message], 'Error');
            return;
        end

        close(f); % Cerrar GUI
    end
end


%% Funcion original sin porcentajes de participacion

% function GUI_Aspirantes
%     % GUI para capturar número de aspirantes y ejecutar informeCompleto.m
% 
%     % Crear ventana
%     f = figure('Name','Captura de Aspirantes', ...
%                'NumberTitle','off', ...
%                'Position',[500 400 400 160], ...
%                'Color','white', ...
%                'MenuBar','none', ...
%                'Resize','off');
% 
%     % Etiqueta
%     uicontrol('Parent',f, 'Style','text', ...
%               'Position',[30 90 150 30], ...
%               'String','Número de Aspirantes:', ...
%               'FontSize',12, ...
%               'HorizontalAlignment','left', ...
%               'BackgroundColor','white');
% 
%     % Caja de texto
%     hEdit = uicontrol('Parent',f, 'Style','edit', ...
%                       'Position',[200 95 80 30], ...
%                       'FontSize',12, ...
%                       'BackgroundColor','white');
% 
%     % Botón Aceptar
%     uicontrol('Parent',f, 'Style','pushbutton', ...
%               'String','Aceptar', ...
%               'FontSize',12, ...
%               'Position',[140 30 120 40], ...
%               'BackgroundColor',[0.4 0.4 0.4], ...
%               'ForegroundColor','white', ...
%               'Callback',@(src,event) aceptarValor());
% 
%     % Función del botón
%     function aceptarValor()
%         valor = str2double(get(hEdit, 'String'));
% 
%         if isnan(valor) || valor < 1 || mod(valor,1) ~= 0
%             errordlg('Ingrese un número entero válido de aspirantes','Error');
%             return;
%         end
% 
%         assignin('base','Aspirantes',valor); % Enviar al workspace
%         try
%              
%               run('VotoPorBloque.m');        % Ejecutar script
%         catch ME
%             errordlg(['Error en el script: ' ME.message], 'Error');
%             return;
%         end
%         close(f); % Cerrar la GUI
%     end
% end
